name: Python application test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test ${{ matrix.test-dir }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-dir:
          - './backend/itemService/borrowItem/'
          - './backend/itemService/createItem/'
          - './backend/itemService/deleteItem/'
          - './backend/itemService/getItemPage/'
          - './backend/itemService/returnItem/'
          - './backend/itemService/updateItem/'
          - './backend/itemService/requestItem/'
          - './backend/itemService/getLenderItems/'
          - './backend/itemService/getBorrowedItems/'
          - './backend/itemService/getItemFromID/'
          - './backend/itemService/cancelRequest/'
          - './backend/userService/createAccount/'
          - './backend/userService/deleteAccount/'
          - './backend/userService/getAccount/'
          - './backend/userService/updateAccount/'
          - './backend/userService/updateAverageAccountRating/'
        
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip3 install pytest boto3 moto
        pip3 install -r ${{ matrix.test-dir }}requirements.txt

    - name: Run tests in ${{ matrix.test-dir }}
      env:
        ENV: testing
      run: |
        cd ${{ matrix.test-dir }}
        python3 -m pytest
      
